modulo003-python-web/20221105_aula09/01_exercicio/financas_pessoais/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('registration/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('register/', include('register.urls'))
]

modulo003-python-web/20221105_aula09/01_exercicio/register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('new/', views.new, name='new')
]

modulo003-python-web/20221105_aula09/01_exercicio/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:user_id>/', views.detail, name='detail'),

    # Contas do usuário
    path('me/accounts/create', views.create_account, name='create_account'),
    path('me/accounts', views.list_accounts, name='list_accounts'),

    # Transações
    path('me/transactions/create', views.create_transaction, name='create_transaction'),
    path('me/transactions', views.list_transactions, name='list_transactions')
]

modulo003-python-web/20221105_aula09/01_exercicio/accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    balance = models.FloatField(default=0)

    class Meta:
        db_table = 'tb_accounts'

    def __str__(self):
        return self.name


class Transaction(models.Model):
    debit_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='debit_account')
    credit_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='credit_account')
    value = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'tb_transactions'

modulo003-python-web/20221105_aula09/01_exercicio/register/models.py
from django.db import models

# Create your models here.

modulo003-python-web/20221105_aula09/01_exercicio/users/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField()

    class Meta:
        db_table = 'tb_profiles'

modulo003-python-web/20221105_aula09/01_exercicio/accounts/views.py
from django.shortcuts import render

# Create your views here.

modulo003-python-web/20221105_aula09/01_exercicio/register/views.py
from django.shortcuts import render
from django.contrib.auth.models import User


def new(request):
    if request.method == 'GET':
        return render(request, 'register/new.html')
    elif request.method == 'POST':
        post_data = request.POST

        u = User(
            username=post_data.get('txtUsername'),
            email=post_data.get('txtEmail'),
            first_name=post_data.get('txtFirstName'),
            last_name=post_data.get('txtLastName')
        )

        # Criptografa a senha do usuário. Isso é necessário para o usuário
        # poder fazer o login
        u.set_password(post_data.get("txtPassword"))
        u.save()

        return render(request, 'register/success.html')

modulo003-python-web/20221105_aula09/01_exercicio/users/views.py
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from accounts.models import Account, Transaction


def index(request):
    # Como pegar o user?
    # request.user -> Usuário atualmente logado
    total_num_accounts = request.user.account_set.all().count()
    # Transaction => Account => User
    # Dessa maneira, conseguirmos pegar todas as transações onde:
    # A conta de débito pertence ao usuário que está armazenado em
    # request.user
    total_num_transactions = Transaction.objects.filter(debit_account__user=request.user).count()

    context = {
        'total_num_accounts': total_num_accounts,
        'total_num_transactions': total_num_transactions
    }

    return render(request, 'users/index.html', context=context)


def detail(request: HttpRequest, user_id: int) -> HttpResponse:

    return render(request, 'users/detail.html')


def create_account(request):

    if request.method == 'GET':
        return render(request, 'accounts/create.html')

    elif request.method == 'POST':

        post_data = request.POST

        if len(post_data.get("txtInitialBalance").strip()):
            balance = float(post_data.get("txtInitialBalance").strip())
        else:
            balance = 0

        account = Account(
            user=request.user,
            name=post_data.get("txtAccountName"),
            balance=balance
        )

        account.save()

        # reverse() converte um padrão de nome de rota para uma URL
        # Por exemplo, a linha abaixo reverse('users:list_accounts',))
        # Será convertida para a URL http://127.0.0.1:8000/users/me/accounts
        return HttpResponseRedirect(reverse('users:list_accounts',))


def list_accounts(request):

    # Pega todas as contas associadas ao usuário logado
    user_accounts = request.user.account_set.all()

    context = {
        'user_accounts': user_accounts
    }

    return render(request, 'accounts/list.html', context=context)


def create_transaction(request):
    if request.method == 'GET':
        all_user_accounts = request.user.account_set.all()

        context = {
            'all_user_accounts': all_user_accounts
        }

        return render(request, 'transactions/create.html', context=context)
    elif request.method == 'POST':

        debit_account_id = request.POST['menuDebitAccount']
        credit_account_id = request.POST['menuCreditAccount']
        value = float(request.POST['txtValue'])

        debit_account = Account.objects.get(pk=debit_account_id)
        credit_account = Account.objects.get(pk=credit_account_id)

        transaction = Transaction(
            debit_account=debit_account,
            credit_account=credit_account,
            value=value
        )

        transaction.save()

        debit_account.balance = debit_account.balance - value
        credit_account.balance = credit_account.balance + value

        debit_account.save()
        credit_account.save()

        return HttpResponseRedirect(reverse('users:index',))


def list_transactions(request):

    transactions = Transaction.objects.filter(debit_account__user=request.user).all()

    context = {
        'transactions': transactions
    }

    return render(request, 'transactions/index.html', context=context)

modulo003-python-web/20221105_aula09/01_exercicio/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Gestor de Finanças Pessoais</title>
  </head>
  <body>
    {% block content %}
      <h1>Hello, world!</h1>
    {% endblock %}

    {% block footer %}{% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

modulo003-python-web/20221105_aula09/01_exercicio/users/templates/accounts/create.html
{% extends 'base.html' %}

{% block content %}
    <div class="container border border-dark mt-2" style="max-width: 480px">
        <div class="row mt-4">
            <div class="col align-self-center text-center">
                CADASTRE A SUA CONTA
            </div>
        </div>
        <form action="{% url 'users:create_account' %}" method="POST">
            {% csrf_token %}
            <div class="row my-2">
                <div class="col">
                    <input
                            type="text"
                            name="txtAccountName"
                            class="form-control"
                            placeholder="Informe o nome da conta"
                    >
                </div>
            </div>
            <div class="row my-2">
                <div class="col">
                    <input
                            type="number"
                            name="txtInitialBalance"
                            class="form-control"
                            placeholder="Informe o saldo inicial da conta"
                    >
                </div>
            </div>
            <div class="row mb-2">
                <div class="col d-flex justify-content-center">
                    <button class="btn btn-primary" type="submit">Cadastrar</button>
                </div>
            </div>
            </form>
    </div>
{% endblock %}

modulo003-python-web/20221105_aula09/01_exercicio/users/templates/accounts/list.html
{% extends 'base.html' %}

{% block content %}
    <div class="row mb-3">
        <h1 class="col text-center">Lista de contas</h1>
    </div>
    <hr>
    <div class="row mb-1">
        <div class="col text-center border-bottom">
            Nome da conta
        </div>
        <div class="col border-bottom">
            Saldo
        </div>
    </div>
    {% for user_account in user_accounts %}
        <div class="row mb-2">
            <div class="col text-center">
                {{ user_account.name }}
            </div>
            <div class="col">
               {{ user_account.balance }}
            </div>
        </div>
    {% endfor %}
    <div>
        <div class="row-mt-3">
            <div class="col">
                <a href="{% url 'users:index' %}">Voltar para a página principal</a>
            </div>
        </div>
        <div class="row-mt-3">
            <div class="col">
                <a href="{% url 'users:create_account' %}">Criar uma nova conta</a>
            </div>
        </div>
    </div>

{% endblock %}

modulo003-python-web/20221105_aula09/01_exercicio/users/templates/users/detail.html
{% extends 'base.html' %}

{% block content %}
    <h2>User detail</h2>
{% endblock %}

modulo003-python-web/20221105_aula09/01_exercicio/users/templates/users/index.html
{% extends 'base.html' %}

{% block content %}
    {% if not user.is_authenticated %}
        <h2 class="text-warning text-center">Você não está logado!</h2>
    {% else %}
        <h2 class="text-dark text-center">Você está logado como {{ user.username }}.</h2>
        <hr>
        <div class="row">
            <div class="col d-flex justify-content-center">
                <p>
                    Você tem atualmente <strong>{{ total_num_accounts }}</strong> contas cadastradas.
        <!--
            O link irá direcionar para a página de cadastro de conta ('/users/me/accounts/create')
            Essa rota irá mostrar um página que possui um formulário com 2 campos:
                - Nome da conta
                - Saldo Inicial (Terá que aparecer com o valor 0)
            Haverá um botão de confirmar o cadastro. Os dados estando corretos, o usuário irá ser
            redirecionado para a página de listagem de contas ('/users/me/accounts')
            A nova conta deve aparecer nessa listagem

            Se o usuário tiver ao menos uma conta cadastrada, o link vai mudar:
                - O texto será "Acesse a página de contas"
                - O link vai direcionar agora para '/users/me/accounts'

        -->
                    {% if total_num_accounts == 0 %}
                        <a href="{% url 'users:create_account' %}">Cadastre a primeira</a>
                    {% else %}
                        <a href="{% url 'users:list_accounts' %}">Acesse a página de contas</a>
                    {% endif %}
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col d-flex justify-content-center">
                <p class="mx-1">Você realizou um total de <strong>{{ total_num_transactions }}</strong> transações.</p>
                {% if total_num_transactions == 0 %}
                    <a href="{% url 'users:create_transaction' %}">Cadastre a primeira transação</a>
                {% else %}
                    <a href="{% url 'users:list_transactions' %}">Vá para a página de listagem de transações</a>
                {% endif %}
            </div>
        </div>

    {% endif %}
{% endblock %}