modulo003-python-web/20221029_aula08/biblioteca/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalogo/', include('catalogo.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/catalogo/'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

modulo003-python-web/20221029_aula08/catalogo/urls.py
from django.urls import path
from . import views

app_name = "catalogo"

urlpatterns = [
    path("", views.index, name="index"),
    path("livros/", views.LivroListView.as_view(), name="lista-livros"),
    path("livros/<int:pk>/", views.LivroDetailView.as_view(), name="detalhe-livro"),
    path("livros/<uuid:pk>/renovar", views.renovar_data_devolucao_livro, name="renovar-data-devolucao-livro"),
    path("livros/<int:pk>/comentar", views.comentar_livro, name="comentar-livro"),
    path("autores/", views.AutorListView.as_view(), name="lista-autores"),
    path("autores/<int:pk>/", views.AutorDetailView.as_view(), name="detalhe-autor"),
    path("meus-emprestimos/", views.CopiasEmprestadasPorUsuarioListView.as_view(), name="meus-emprestimos"),
    path("todos-os-emprestimos/", views.TodasAsCopiasEmprestadasListView.as_view(), name="todas-as-copias-emprestadas")
]

modulo003-python-web/20221029_aula08/catalogo/models.py
from datetime import date
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Genero(models.Model):

    # help_text é o texto que aparecerá no admin do Django
    nome = models.CharField(max_length=200, help_text="Informe um gênero literário (Ficção Científica, Terror, etc)")

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'tb_generos'


class Livro(models.Model):

    titulo = models.CharField(max_length=200)
    autor = models.ForeignKey('Autor', on_delete=models.SET_NULL, null=True)
    sumario = models.TextField(max_length=100, help_text="Informe uma breve descrição do livro")
    isbn = models.CharField("ISBN", max_length=13, help_text="Informe o ISBN (13 caracteres)")
    genero = models.ManyToManyField(Genero, help_text="Informe um gênero para esse livro")

    # Esse método será usado para mostrar o(s) gênero(s) associado(s) a esse livro
    def mostrar_genero(self):
        # Retorna uma string com a lista dos gêneros que estão associados a esse livro
        return ', '.join([genero.nome for genero in self.genero.all()])

    # 'short_description' será o nome da coluna onde esse(s) gênero(s) serão listados
    mostrar_genero.short_description = "Gênero(s)"

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('catalogo:detalhe-livro', args=[str(self.id)])

    class Meta:
        db_table = 'tb_livros'


class CopiaLivro(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="ID da cópia")
    livro = models.ForeignKey(Livro, on_delete=models.RESTRICT, null=True)
    impressao = models.CharField(max_length=200)
    devolucao = models.DateField(null=True, blank=True)
    emprestado_para = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    STATUS_COPIA = (
        ('m', 'Manutenção'),
        ('e', 'Emprestado'),
        ('d', 'Disponível'),
        ('r', 'Reservado'),
    )

    status = models.CharField(
        max_length=1,
        choices=STATUS_COPIA,
        blank=True,
        default='m',
        help_text="Disponibilidade da cópia"
    )

    def __str__(self):
        return f'{self.id} ({self.livro.titulo})'

    class Meta:
        db_table = 'tb_copias'
        ordering = ['devolucao']

        # O atributo permissions permite que criemos permissões personalizadas para a model. Esse campo
        # deve ser uma tupla de tuplas
        # O primeiro item da tupla deve ser o nome que será dado a ela, e o segundo é uma descrição.
        # Após a a(s) permissão(ões) for criada, precisamos gerar uma migration e aplicá-la, para a
        # permissão ser salva na tabela de permissões
        permissions = (("pode_marcar_copia_como_devolvida", "Marca a cópia como devolvida"),)

    @property
    def emprestimo_vencido(self):
        return bool(self.devolucao and date.today() > self.devolucao)


class Autor(models.Model):

    nome = models.CharField(max_length=50)
    sobrenome = models.CharField(max_length=100)
    data_de_nascimento = models.DateField("Nascimento (\u2605)", null=True, blank=True)
    data_de_falecimento = models.DateField("Falecimento (\u271F)", null=True, blank=True)

    def __str__(self):
        return f'{self.sobrenome}, {self.nome}'

    def get_absolute_url(self):
        return reverse('catalogo:detalhe-autor', args=[str(self.id)])

    class Meta:
        ordering = ['sobrenome', 'nome']


class OpiniaoUsuarioLivro(models.Model):
    livro = models.ForeignKey(Livro, on_delete=models.SET_NULL, null=True, blank=True)
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    comentario = models.TextField()

    NOTA_LIVRO = (
        ("1", "Odiei"),
        ("2", "Não gostei"),
        ("3", "Neutro"),
        ("4", "Gostei"),
        ("5", "Amei")
    )

    nota = models.CharField(
        max_length=1,
        choices=NOTA_LIVRO,
        blank=True,
        default='3',
        help_text="Nota do livro segundo o usuário"
    )

    def __str__(self):
        return self.comentario

    class Meta:
        db_table = "opinioes_usuarios_livros"

modulo003-python-web/20221029_aula08/catalogo/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
# gettext_lazy é uma função para internacionalizar o programa (trocar strings)
from django.utils.translation import gettext_lazy as _


class RenovarDevolucaoLivro(forms.Form):
    nova_data_de_devolucao = forms.DateField(
        help_text="Insira a nova data de devolução do livro, sendo no máximo daqui a 4 semanas (3 por padrão)"
    )

    # Se quisermos aplicar algum tipo de validação nos campos do formulário, usamos o método
    # clean_<nome_do_campo>
    def clean_nova_data_de_devolucao(self):

        # O dicionário self.cleaned_data contém os dados do formulário que já foram pré-validados
        # pelos validadores padrão do Django (caracteres especiais, encoding, etc)
        data = self.cleaned_data["nova_data_de_devolucao"]

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_("Data de renovação inválida - Maior do que 4 semanas"))

        if data < datetime.date.today():
            raise ValidationError(_("Data de renovação inválida - Menor que a data atual"))

        # Sempre lembrar de retornar o dado validado
        return data

modulo003-python-web/20221029_aula08/catalogo/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required, login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
import datetime

from .forms import RenovarDevolucaoLivro
from .models import Livro, CopiaLivro, Autor, OpiniaoUsuarioLivro


# function-based view
# Caso queiramos usar permissões em function-based views, importamos o decorator permission_required
# e aplicamos na function based view
# O decorator login_required serve pra limitar o acesso à view apenas aos usuários logados
# @login_required()
# @permission_required("catalogo.pode_marcar_copia_como_devolvida")
def index(request):

    qtd_livros = Livro.objects.count()
    qtd_copias = CopiaLivro.objects.count()

    # filter -> WHERE
    qtd_copias_disponiveis = CopiaLivro.objects.filter(
        status__exact='d'
    ).count()

    qtd_autores = Autor.objects.count()
    qtd_visitas = request.session.get("qtd_visitas", 0)

    request.session['qtd_visitas'] = qtd_visitas + 1
    request.session['ultimo_acesso'] = datetime.datetime.now().strftime(
        "%d/%m/%Y %H:%M:%S"
    )

    context = {
        'qtd_livros': qtd_livros,
        'qtd_copias': qtd_copias,
        'qtd_copias_disponiveis': qtd_copias_disponiveis,
        'qtd_autores': qtd_autores,
        'qtd_visitas': qtd_visitas,
        'ultimo_acesso': request.session.get('ultimo_acesso')
    }

    return render(request, 'catalogo/index.html', context=context)


@login_required
@permission_required("catalogo.pode_marcar_copia_como_devolvida", raise_exception=True)
def renovar_data_devolucao_livro(request, pk):

    copia = get_object_or_404(CopiaLivro, pk=pk)

    if request.method == "POST":
        form = RenovarDevolucaoLivro(request.POST)

        # o método is_valid() chama os validadores do form, tanto os padrões quanto os definidos pelo programador.
        # Se nenhuma exceção for gerada, esse método retorna True
        if form.is_valid():
            copia.devolucao = form.cleaned_data["nova_data_de_devolucao"]
            copia.save()

            return HttpResponseRedirect(reverse("catalogo:todas-as-copias-emprestadas"))

    else:
        nova_data_proposta = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenovarDevolucaoLivro(initial={"nova_data_de_devolucao": nova_data_proposta})

    context = {
        "form": form,
        "copia": copia
    }

    return render(request, "catalogo/renovar_data_devolucao_livro.html", context)


@login_required
def comentar_livro(request, pk):

    livro = get_object_or_404(Livro, pk=pk)

    if request.method == "POST":
        data = request.POST
        OpiniaoUsuarioLivro(
            usuario=request.user,
            livro=livro,
            comentario=data.get("comentario"),
            nota=data.get("nota")
        ).save()

        return HttpResponseRedirect(reverse("catalogo:detalhe-livro", args=(pk,)))

    else:
        context = {
            "livro": livro
        }

        return render(request, "catalogo/comentar_livro.html", context)


# class-based view
class LivroListView(generic.ListView):
    model = Livro
    context_object_name = "livro_list"
    paginate_by = 10

    def get_queryset(self):
        return Livro.objects.order_by("-id").all()


class LivroDetailView(generic.DetailView):
    model = Livro


class AutorListView(generic.ListView):
    model = Autor
    context_object_name = "autor_list"


class AutorDetailView(generic.DetailView):
    model = Autor


# Apenas usuário logados podem acessar essa view, por causa do mixin LoginRequiredMixin
class CopiasEmprestadasPorUsuarioListView(LoginRequiredMixin, generic.ListView):
    model = CopiaLivro
    template_name = 'catalogo/copias_emprestadas_por_usuario.html'
    paginate_by = 10

    # O método get_queryset é chamado quando os dados serão carregados do banco de dados
    # Por padrão, ele trás todos os registros, sem nenhum filtro
    def get_queryset(self):

        lista_copias = CopiaLivro.objects.filter(
            emprestado_para=self.request.user,
            status__exact='e'
        ).order_by('devolucao')

        return lista_copias


class TodasAsCopiasEmprestadasListView(PermissionRequiredMixin, generic.ListView):
    model = CopiaLivro
    template_name = 'catalogo/todas_as_copias_emprestadas.html'
    paginate_by = 10
    permission_required = ("catalogo.pode_marcar_copia_como_devolvida",)

    # O método get_queryset é chamado quando os dados serão carregados do banco de dados
    # Por padrão, ele trás todos os registros, sem nenhum filtro
    def get_queryset(self):

        lista_copias = CopiaLivro.objects.filter(
            status__exact='e'
        ).order_by('devolucao')

        return lista_copias

modulo003-python-web/20221029_aula08/catalogo/templates/catalogo/autor_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ autor.nome }} {{ autor.sobrenome }}</h1>
    <hr>
    <p><strong>Data de nascimento: {% if autor.data_de_nascimento %}{{ autor.data_de_nascimento|date:"d/m/Y" }} {% else %}?{% endif %}</strong></p>
    <p><strong>Data de falecimento: {% if autor.data_de_falecimento %}{{ autor.data_de_falecimento|date:"d/m/Y" }} {% else %}?{% endif %}</strong></p>

    <hr>
    <div style="margin-left: 20px; margin-top: 20px;">
    <h3>Livros</h3>
        {% if autor.livro_set.all %}
            <ul>
                {% for livro in autor.livro_set.all %}
                <li>
                    <a href="{{ livro.get_absolute_url }}">{{ livro }}</a>
                </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Não existem livros desse autor cadastrados na biblioteca</p>
        {% endif %}
    </div>
{% endblock %}

modulo003-python-web/20221029_aula08/catalogo/templates/catalogo/autor_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Lista dos autores</h1>
    {% if autor_list %}
        <ul>
            {% for autor in autor_list %}
                <li><a href="{{ autor.get_absolute_url }}">{{ autor.sobrenome }}, {{ autor.nome }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Não existem autores a serem exibidos.</p>
    {% endif %}
{% endblock %}

modulo003-python-web/20221029_aula08/catalogo/templates/catalogo/comentar_livro.html
{% extends "base.html" %}

{% block content %}
    <h2>Publicar um comentário sobre o livro '{{ livro.titulo }}'</h2>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td>
                    Comentário
                </td>
                <td>
                    <textarea name="comentario" id="comentario" cols="50" rows="10"></textarea>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="odiei">Odiei</label>
                    <input type="radio" id="odiei" name="nota" value="1">

                    <label for="nao_gostei">Não gostei</label>
                    <input type="radio" id="nao_gostei" name="nota" value="2">

                    <label for="neutro">Neutro</label>
                    <input type="radio" id="neutro" name="nota" value="3">

                    <label for="gostei">Gostei</label>
                    <input type="radio" id="gostei" name="nota" value="4">

                    <label for="amei">Amei</label>
                    <input type="radio" id="amei" name="nota" value="5">
                </td>
            </tr>
        </table>
        <input type="submit" value="Salvar">
    </form>

{% endblock %}

modulo003-python-web/20221029_aula08/catalogo/templates/catalogo/copias_emprestadas_por_usuario.html
{% extends 'base.html' %}

{% block content %}
    <h1>Livros emprestados</h1>

    {% if copialivro_list %}
        <ul>
            {% for copialivro in copialivro_list %}
                <li class="{% if copialivro.emprestimo_vencido %}text-danger{% endif %}">
                    <a href="{% url 'catalogo:detalhe-livro' copialivro.livro.pk %}">
                        {{ copialivro.livro.titulo }}
                    </a>
                    (Devolução: {{ copialivro.devolucao|date:'d/m/Y' }})
                    {% if perms.catalogo.pode_marcar_copia_como_devolvida %}
                        - <a href="#">Renovar</a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Você não possui empréstimos em aberto na biblioteca</p>
    {% endif %}
{% endblock %}

modulo003-python-web/20221029_aula08/catalogo/templates/catalogo/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Biblioteca</h1>
    <p>Bem-vindo a página da biblioteca</p>
    <em>Desenvolvido por Proway</em>
    <p>A biblioteca possui os seguintes números</p>
    <ul>
        <li>Quantidade de livros: {{ qtd_livros }}</li>
        <li>Quantidade de cópias: {{ qtd_copias }}</li>
        <li>Quantidade de cópias disponíveis: {{ qtd_copias_disponiveis }}</li>
        <li>Quantidade de autores: {{ qtd_autores }}</li>
    </ul>
    <p>Você visitou essa página {{ qtd_visitas }} vezes</p>
    <p>Data/hora de último acesso: {{ ultimo_acesso }}</p>
{% endblock %}

modulo003-python-web/20221029_aula08/catalogo/templates/catalogo/livro_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>Título: {{ livro.titulo }}</h1>
    <p><strong>Autor: <a href="{{ livro.autor.get_absolute_url }}">{{ livro.autor }}</a></strong></p>
    <p><strong>Sumário: {{ livro.sumario }}</strong></p>
    <p><strong>ISBN: {{ livro.isbn }}</strong></p>
    <p><strong>Gênero(s): {{ livro.genero.all|join:", " }}</strong></p>
    <hr>

    <div style="margin-left: 20px; margin-top: 20px;">
        <h4>Comentários sobre o livro</h4>
        <p><a href="{% url 'catalogo:comentar-livro' livro.id %} ">Fazer comentário</a></p>
        {% if livro.opiniaousuariolivro_set.all %}
            {% for comentario in livro.opiniaousuariolivro_set.all %}
                <p>({{ comentario.nota }}) {{ comentario.comentario }} -- <i>{{ comentario.usuario }}</i></p>
            {% endfor %}
        {% else %}
            <p>Não existem comentários relacionados a esse livro</p>
        {% endif %}
        <hr>
        <h4>Cópias</h4>
        {% for copia in livro.copialivro_set.all %}
            <hr>
            <p>{{ copia.pk }}</p>
            <p class="{% if copia.status == 'd' %}text-success{% elif copia.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copia.get_status_display }}</p>
            {% if copia.status != 'd' %}
                <p><strong>A cópia ficará disponível em {{ copia.devolucao|date:"d/m/Y" }}</strong></p>
            {% endif %}
            <p>{{ copia.impressao }}</p>
        {% endfor %}
    </div>
{% endblock %}

modulo003-python-web/20221029_aula08/catalogo/templates/catalogo/livro_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Lista dos livros</h1>
    {% if livro_list %}
        <ul>
            {% for livro in livro_list %}
                <li><a href="{{ livro.get_absolute_url }}">{{ livro.titulo }}</a> ({{ livro.autor }})</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Não existem livros a serem exibidos.</p>
    {% endif %}
{% endblock %}

modulo003-python-web/20221029_aula08/catalogo/templates/catalogo/renovar_data_devolucao_livro.html
{% extends "base.html" %}

{% block content %}
    <h1>Renovar: {{ copia.livro.titulo }}</h1>
    <p>Emprestado para: {{ copia.emprestado_para }}</p>
    <p {% if copia.emprestimo_vencido %}class="text-danger"{% endif %}>Data de devolução: {{ copia.devolucao|date:"d/m/Y" }} </p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Enviar">
    </form>

{% endblock %}

modulo003-python-web/20221029_aula08/catalogo/templates/catalogo/todas_as_copias_emprestadas.html
{% extends 'base.html' %}

{% block content %}
    <h1>Todas as cópias emprestadas</h1>

    {% if copialivro_list %}
        <ul>
            {% for copialivro in copialivro_list %}
                <li class="{% if copialivro.emprestimo_vencido %}text-danger{% endif %}">
                    <a href="{% url 'catalogo:detalhe-livro' copialivro.livro.pk %}">
                        ({{ copialivro.pk }})
                        {{ copialivro.livro.titulo }}
                    </a>
                    - {{ copialivro.emprestado_para.get_username }}
                    (Devolução: {{ copialivro.devolucao|date:'d/m/Y' }})
                    {% if perms.catalogo.pode_marcar_copia_como_devolvida %}
                        - <a href="{% url 'catalogo:renovar-data-devolucao-livro' copialivro.id %}">Renovar</a>
                    {% endif %}

                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Você não possui empréstimos em aberto na biblioteca</p>
    {% endif %}
{% endblock %}