modulo003-python-web/20220917_aula02/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls")),
    path("store/", include("store.urls"))
]

modulo003-python-web/20220917_aula02/polls/urls.py
from django.urls import path

from . import views

# Aqui criamos um 'namespace' para as rotas. Assim, evitamos algum caso de conflito de rotas, onde o Django não saiba
# em qual pacote uma rota deve ser carregada
app_name = "polls"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results", views.results, name="results"),
    path("<int:question_id>/vote", views.vote, name="vote"),
]

modulo003-python-web/20220917_aula02/store/urls.py
from django.urls import path

from . import views

app_name = "store"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:item_list_id>/detail", views.detail, name="detail")
]

modulo003-python-web/20220917_aula02/polls/models.py
from django.db import models


class Question(models.Model):

    question_text = models.CharField(max_length=100)
    pub_date = models.DateTimeField("Publicada em")

    def __str__(self):
        return self.question_text


class Choice(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

modulo003-python-web/20220917_aula02/store/models.py
from django.db import models


class ItemsList(models.Model):
    name = models.CharField(max_length=200)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.name


class Item(models.Model):
    item_list = models.ForeignKey(ItemsList, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.FloatField(default=0)

    def __str__(self):
        return self.name

modulo003-python-web/20220917_aula02/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404     # Função que vai renderizar o template
from django.urls import reverse

from polls.models import Question, Choice


def index(request):
    # Consulta no banco todas as perguntas, ordenando pela data de publicação (as mais recentes primeiro)
    # Utilizando slice, retorna apenas os  5 primeiros registros
    latest_question_list = Question.objects.order_by("-pub_date")[:5]

    # context é o dicionário de contexto que vamos passar para o template
    # Basicamente, podemos acessar os valores desse dicionário referenciando os nomes das chaves no template
    context = {"latest_question_list": latest_question_list}


    # render() é a função que renderiza (carrega) o template e o retorna como uma resposta HTTP
    # O primeiro argumento da função é o objeto de requisição, que é um argumento obrigatório
    # O segundo argumento é o caminho onde está o template. Por padrão, o django procura os templates dentro do
    # pacote atual, em uma pasta chamada templates. Se ele encontra essa pasta, tudo que é colocado depois é considerado
    # como o caminho para carregar o template
    # Por último, podemos passar o dicionário de contexto, dessa maneira podemos passar os valores que carregamos
    # no backend da aplicação para o frontend. Basicamente, referenciamos as chaves do dicionário de contexto como
    # variáveis dentro do template
    return render(request, "polls/index.html", context=context)


def detail(request, question_id):
    # Pegamos o id da pergunta que vem via URL, e carregamos essa pergunta do banco de dados
    # A função get_object_or_404 verifica se o registro que está sendo consultado realmente existe na tabela.
    # Se exister, ele retorna o objeto. Se não, ele retorna uma erro HTTP 404 (Not Found)
    question = get_object_or_404(Question, pk=question_id)

    return render(request, "polls/detail.html", context={"question": question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    try:
        # pk = primary key
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "polls/detail.html", {
            "question": question,
            "error_message": "Você deve escolher uma opção válida!"
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

    return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

modulo003-python-web/20220917_aula02/store/views.py
from django.shortcuts import render, get_object_or_404
from .models import ItemsList


def index(request):

    all_items_list = ItemsList.objects.all()
    context = {"all_items_list": all_items_list}
    return render(request, "store/index.html", context)


def detail(request, item_list_id):

    items_list = get_object_or_404(ItemsList, pk=item_list_id)
    context = {"items_list": items_list}
    return render(request, "store/detail.html", context)

modulo003-python-web/20220917_aula02/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="POST">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question }}</h1></legend>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice }}</label><br>
        {% endfor %}
    </fieldset>
    <br>
    <input type="submit" value="Votar">
</form>

modulo003-python-web/20220917_aula02/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <!-- A função de template url carrega o caminho da rota a partir do nome que foi indicado (no caso abaixo, "detail").
                Se na URL é esperado ser recebido algum argumento (padrão que começa com '<' e termina com '>', então
                precisamos passar esse(s) argumento(s) após o nome da rota. No caso abaixo, como a rota detail recebe
                via url um argumento chamado question_id, precisamos passar um valor pra esse argumento
        -->
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>Não existem perguntas cadastradas</p>
{% endif %}

modulo003-python-web/20220917_aula02/polls/templates/polls/results.html
<h1>{{ question }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice }} -- {{ choice.votes }} voto{{ choice.votes|pluralize:"s" }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Votar novamente</a><br>
<a href="{% url 'polls:index' %}">Voltar a listagem de perguntas</a>

modulo003-python-web/20220917_aula02/store/templates/store/detail.html
<h1>{{ items_list }}</h1>
<hr><br>

<ul>
    {% for item in items_list.item_set.all %}
        <li>Nome: <stron>{{ item.name }}</stron></li>
        <li>Preço: <strong>{{ item.price }}</strong></li>
        <hr>
    {% endfor %}
</ul>

modulo003-python-web/20220917_aula02/store/templates/store/index.html
{% if all_items_list %}
    <ul>
        {% for items_list in all_items_list %}
            <li><a href="{% url 'store:detail' items_list.id %}">{{ items_list }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h2>Não existem listas de items a serem exibidas.</h2>
{% endif %}